repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: validate-toml
    - id: golangci-lint
    - id: go-critic
    - id: go-mod-tidy
    - id: go-build